### ISSUE TITLE
no match function (%.%) exists

### ISSUE THREAD

**Issue by FloraHY** [jcheng5/googleCharts#10]
Hi cheng, when I apply this app to visualize my dataset, the webpage doesn't show anything but the error warning: no match function (%.%) exists. could u please tell me how to fix it ? so many thx for your help!!
df <- data %.%
      filter(Year == input$year) %.%
      select(Country, Health.Expenditure, Life.Expectancy,
        Region, Population) %.%
      arrange(Region)

and my code is below one:
  df<- weather%.%
      filter_(Year == input$year)%.%
              select(district,PRCP,injuries,
                    region, SNWD)%.%
             arrange(region)

**Comment by jcheng5** [comment]
Closing this old issue, hopefully you figured out that it should be `%>%`!
